### ISSUE TITLE
vmlib64.exe error when attempting to start vmware vm inside gns3

### ISSUE THREAD

**Issue by codeassassin** [GNS3/gns3-gui#1648]
@noplay , I am also having issues running VMware VMs inside GNS3. I experienced two issues. 

1)When I go to run the VM, GNS3 appears to try, unsuccessfully, to install Virtual NICs. However, after losing internet access to my host workstation, I discovered that not only had GNS3 installed a mother-load of vnet nic cards, VMware Worstation doesn't recognize the addition of said nvet cards, and it appears that the vnet interfaces I had configured for my other VMware VMs has been overwritten. Major bummer and major headache. What I did to experience this was, after reading the error statement after starting the VM, I went to the VMware network settings like it stated, and then I just clicked the little "configure" button, as stated in the console output. I should not have clicked the little configure button. 

![gns3networkbug](https://cloud.githubusercontent.com/assets/6335629/20006551/65a44210-a26e-11e6-9fe7-f8d670df4af5.jpg)

![gns3networkbug2](https://cloud.githubusercontent.com/assets/6335629/20006630/d5df7194-a26e-11e6-9fa8-1db1ed72788c.jpg)

2) After cycling through 19 error windows for the vnet nics I really didn't want created, and certainly didn't want overwritten, I right-clicked and attempted to start the VM again. This time, VMware Workstation does begin to start the VM. However, GNS3 waits what appears to be 5 seconds and throws an error that the VM didn't start. Even with an SSD, it's not going to start that fast.

![image](https://cloud.githubusercontent.com/assets/6335629/20006696/2dff94e4-a26f-11e6-8d16-1a94947cf629.png)

**Comment by codeassassin** [comment]
FYI, to resume vmnet nic functionality of VMWare Workstation VMs after "configure" command is clicked, you have to execute the following steps to get adapters working again for VMware Workstation VMs:

1) Inside Virtual Network Editor, install all the vmnet adapters that were installed by GNS3. 
2) Delete ALL vmnet adapters, including the ones that were already installed prior to GNS3 configure button.
3) Reinstall ALL vmnet adapters needed to be run inside VMWare Workstation.

**Comment by noplay** [comment]
I just test and I don't reproduce the missing DLL  :( 

Their is nothing complex we look in the registry database where is installed VMware and we call their utilities for creating vmnet.

I just made a new build that will display where we are looking for VMware utilities
https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2016-11-11/2.0/GNS3-2.0.2016-11-11-all-in-one.exe/download

I suspect we call an old installation of VMware where some stuff are missing.

**Comment by codeassassin** [comment]
I'm trying to remember at what point I encountered this error. It may have been when I clicked the configure button inside Preferences > VMware > Network > "configure"

**Comment by noplay** [comment]
Yes it should be here

**Comment by codeassassin** [comment]
I just retried and observed the same error message. I'm not sure if you wanted me to provide any additional information. Just let me know.

**Comment by noplay** [comment]
If you use last nightly https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/ when vmnet.exe start the path display at the top is correct?

**Comment by codeassassin** [comment]
Well, the path at the top is 

```C:\Program Files (x86)\VMware\VMware Workstation\vnetlib.exe```

The error is thrown by vnetlib64.exe stating VNETLIB.DLL is missing. However, there is a VMETLIB64.DLL. It is possible GNS3 should be calling 

``````C:\Program Files (x86)\VMware\VMware Workstation\vnetlib64.exe```

instead? Thanks!

**Comment by noplay** [comment]
Thank I will add this case. No idea why on your PC this DLL is not installed

**Comment by jjpetsche** [comment]
I'm having this same error.

**Comment by rendezvoush** [comment]
I still have this same error with GNS3 version  2.0.2 and VMware Workstaion Pro 12.5.5 build-5234757.

**Comment by kuroboshi** [comment]
Hello,
I still have this same error so i add the ddl on C:\Program Files\GNS3 and it's works.

**Comment by rendezvoush** [comment]
@noplay I got the issue resolved by  adding  my VMware installation directory on the PATH environment variable.  

Thanks a lot

**Comment by tsfstarr** [comment]
@kuroboshi is correct.
This is still a problem for 2.1.5 in Windows 7 SP1.
I copied the following files from my VMware Player installation to "C:\Program Files\GNS3":
vnetlib.dll
vnetlib64.dll
vnetlib.exe
vnetlib64.exe

I have no idea why this fixes the problem!

**Comment by grossmj** [comment]
I have changed the way we look for vnetlib, hopefully this will fix this issue.

https://github.com/GNS3/gns3-server/commit/051eedb4067b3fed35bb0e310798b00ca5f34799
