### ISSUE TITLE
#2111 Still reproducible - GNS3 client packet capture not working correctly when remote main server is configured

### ISSUE THREAD

**Issue by nextai2003** [GNS3/gns3-gui#2350]
Client / Server version : 2.1.0

Sorry, I tried to reopen issue #2111 but it seems I don't have the rights. This is why I logged a new issue.

Steps to reproduce:

Configure a VMWare Workstation image (GNS3.VM.VMware.Workstation.2.1.0) as remote main server in the GNS3 Windows client Tested with Wireshark x64 2.0.x and 2.2.7

Create a topology between multiple QEMU devices (e.g. Linux TinyCore).

Start packet capture on the link via GUI (right-click on link, capture).

At step 3, you shall notice that Wireshark starts correctly and scrolls packets in realtime.

Stop Wireshark, exit it and then stop capture from GUI via right-click "Stop capture".
At step 4, you will receive an error in the GUI's console similar to "Can't remove file C:/Users/Emanuel/AppData/Local/Temp/GNS3.Os2808" - opening the temp dir will not reveal this file. You will however notice another GNS3.Sh2808 or similar named file which is 0 KB in length and locked by the GUI (you can't remove it). In time, you will notice that this file keeps growing, meaning that actually the packet capture is still in process in this new file.

Try to start capture again. This time wireshark opens but does not scroll the capture.

Repeat steps 4 and 5. Even from the first repetition you may notice that wireshark throws "invalid packet size" when trying to display the capture, so the capture gets somehow corrupted. Also, after few repetitions, almost every time the remote main server stopped responding (timeout when accessing computes message).

Please note that this issue does not occur when using the local server with the standard "remote servers" configuration (when you are using the VM as a standard remote server).

**Comment by grossmj** [comment]
This should fix the issue but still needs to be tested: https://github.com/GNS3/gns3-gui/commit/9ca35c56de6c6eaedcdbfc1a7ae70018ac8deff8

**Comment by nextai2003** [comment]
Thank you, I compiled the committed file and tested your fix. There is progress, but still an issue is left:

1. Start capture - everything works fine.
2. Stop capture - seems to stop correctly, the error message ("Can't remove file ...") is no longer displayed.
3. Start capture - following error message is displayed: "Can't create capture file /opt/gns3/projects/1fc8fa88-6598-44bc-8670-58047b96f2ad/project-files/captures/TinyCore_Linux_64-1_eth0_to_SW1_Gi0.pcap: [Errno 2] No such file or directory: '/opt/gns3/projects/1fc8fa88-6598-44bc-8670-58047b96f2ad/project-files/captures/TinyCore_Linux_64-1_eth0_to_SW1_Gi0.pcap'"

Probably, the second time the capture is started, it is trying to create the capture file on the server instead of on the client (I am guessing the temp capture should be created on the client ?).

Thanks much for your support.

**Comment by grossmj** [comment]
I tried to reproduce the issue with 2 Qemu nodes running on a GNS3 VM configured as a remote server in the GUI. I could not get the error you have. Maybe you could do a short video or post snapshots to help us?

Thank you.

**Comment by nextai2003** [comment]
Hello, many apologies for not responding in such a long time, I have had some personal issues to take care of .. I see that the issue is reported on a newer version by ziajka and tlsalex in #2438, so maybe we can track the problem in there.

My regards to you and thanks for all your support and work.

**Comment by grossmj** [comment]
This problem is fixed in the soon to be released GNS3 version 2.1.4. Please open a new issue if you still experience something wrong on your side.

**Comment by nextai2003** [comment]
Thank you very much !
