### ISSUE TITLE
Stopping and starting a wireshark capture bug

### ISSUE THREAD

**Issue by sliddjur** [GNS3/gns3-gui#2438]
When I stop a wireshark capture, and then continue the wireshark capture another time, I will only see the old packet capture. Wireshark will not capture any new frames. It doesn't matter if I shutdown port, reload switch, restart GNS3. Doesn't matter if if I give the capture a new name in the Wireshark window. 

The solution is to go into GNS3 VM and go into /opt/gns3/projects/xxxx/project-files/captures/ and delete the pcap files manually. Then start capture again.

Setup:
Client: GNS3 2.1.3 (Ubuntu 17.10 and Windows 10)
No local server, only "Remote main server".

**Comment by ziajka** [comment]
Thank you @sliddjur.
Possible related to https://github.com/GNS3/gns3-gui/issues/2427

**Comment by sliddjur** [comment]
Probably is, yes @ziajka

**Comment by ziajka** [comment]
And to: https://github.com/GNS3/gns3-gui/issues/2350

**Comment by tlsalex** [comment]
I have the same problem with GNS3 2.1.3 (Windows 8.1)

**Comment by tlsalex** [comment]
cc @grossmj

**Comment by grossmj** [comment]
Fixed by https://github.com/GNS3/gns3-server/commit/38f458db7c0e5a193001803bfe54efde2c9efa90

**Comment by EB-athila** [comment]
Issue still present  on GNS3 2.1.8 vm (Win8.1 & Win10) .
I've notice that with the second capture try, the pcap file stops growing. Also, even if all captures and nodes are stopped, and I try to delete the project, I can't because pcap file "still in use".  Can't delete a project after any capture is started/stopped.

**Comment by EB-athila** [comment]
No problem with MacOS version. It seems to be that a process is unable to release the pcap file after capture is stopped, preventing new processes to write on it.
Workaround: Change pcap filename on every capture. It won't allowed to delete the project, though.

**Comment by grossmj** [comment]
@EB-athila did you use WinPcap or Npcap?

**Comment by EB-athila** [comment]
Npcap.

![image](https://user-images.githubusercontent.com/21137156/44747223-a4d7d200-aada-11e8-8fc8-dba810c6bbb2.png)

**Comment by grossmj** [comment]
@EB-athila there is a known problem with NPCAP: https://github.com/nmap/nmap/issues/997 which may be the reason why you have this issue. Can you test with WinPcap instead and see if you can reproduce this issue?

Thanks! :)

**Comment by EB-athila** [comment]
Uninstalled npcap and reinstalled winpcap. I'm still having this issue.

**Comment by grossmj** [comment]
Ok, thanks for the confirmation. I will see if I can fix this before we release version 2.1.10.

**Comment by grossmj** [comment]
I have identified the reason: pcap file streaming on compute server is not stopped and because of file locking on Windows, another packet capture cannot be started with on a same pcap file.

Unfortunately there are too many changes to make in order to have everything work properly in the 2.1.x version, we don't really want to break something now. I will push this for version 2.2.

The workaround at the moment is to use a different file name every time a new capture is started on Windows for devices running on remote server or the GNS3 VM.

**Comment by mladenradev** [comment]
Hi Jeremy, I have "similar" issue with VM setup and Linux client (2.1.9 server and client). Wireshark starts without problem, but after a while data stop arriving in the local file. Do you have any idea why or some workaround?

**Comment by int3l** [comment]
Hi, @grossmj I can confirm this bug. I looked at the code and it seems that the tail sub process in GNS3 that reads the captured data doesn't terminate, when you stop the capturing (via the 'Stop capture' button on the link or if you open another project and then go back to the older capturing project).

@mladenradev this is a different kind of problem. Please open new issue and describe how you hit this scenario (if possible - step by step and with details for OS version and etc). The current issue is not directly related. As a workaround I can recommend upgrading or at least testing the same set of actions on the latest GNS3 (which currently is 2.1.11).

**Comment by cioby23** [comment]
This issue is fixed in the next release 2.2 not in 2.1.x versions which you are currently using.

**Comment by sliddjur** [comment]
I have also noticed recently that captures  stop completely on my remote server. Restarting the capture DOES start the capture again. Im not sure it matters what OS I am running, or topology, but it happens quite often. I am currently running gns3 2.11. esxi server. gns3 gui on windows 10 and ubuntu 18.10.
guests are cumulus os

Is this related to the tmp file bug?

**Comment by lostlsend** [comment]
> Hi Jeremy, I have "similar" issue with VM setup and Linux client (2.1.9 server and client). Wireshark starts without problem, but after a while data stop arriving in the local file. If I restart capture from Wireshark - no change. If I stop and start capture from GUI - wireshark showing some data and stops after a while. Do you have any idea why or some workaround?

I am confronted with the exact same issue.
