### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-gui#2566]
Environment: Linux (Archlinux), Python version 3.7, GNS3 version 2.1.9

GNS3 gui doesn't start when using python 3.7. Below is the trace from the gns3_gui.log file

2018-08-22 19:16:38 INFO main.py:259 GNS3 GUI version 2.1.9
2018-08-22 19:16:38 INFO main.py:260 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-08-22 19:16:38 INFO main.py:262 Application started with /usr/bin/gns3
2018-08-22 19:16:44 ERROR local_server.py:487 Local server process has stopped
2018-08-22 19:16:44 ERROR local_server.py:489 Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server==2.1.9', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.7/site-packages/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.7/site-packages/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.7/site-packages/gns3server/web/web_server.py", line 26, in <module>
    import aiohttp
  File "/usr/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 13, in <module>
    from . import hdrs, helpers
  File "/usr/lib/python3.7/site-packages/aiohttp/helpers.py", line 30
    **ensure_future = asyncio.async**
                                ^
SyntaxError: invalid syntax

2018-08-22 19:17:09 CRITICAL progress_dialog.py:181 WaitForConnectionWorker thread stopping with an error: Could not connect to x.x.x.x on port 8080: [Errno 111] Connection refused
2018-08-22 19:17:09 CRITICAL __init__.py:183 Could not connect to x.x.x.x on port 8080: [Errno 111] Connection refused

I have manually modified the line **ensure_future = asyncio.async** into **ensure_future = asyncio.ensure_future** and it's starts properly. I think it's related to the https://github.com/GNS3/gns3-server/issues/1370

**Comment by grossmj** [comment]
@ziajka should we backport https://github.com/GNS3/gns3-server/commit/d9a0ec9ff374394d11c11e6939881e50bf570091 and https://github.com/GNS3/gns3-server/commit/eeae07e783856c60ed0edecc6ea1c845d16bc28b to version 2.1.10?

**Comment by ziajka** [comment]
I think it might be necessary. Minus is that on 2.1 there is no alpha version so we cannot verify it.

**Comment by grossmj** [comment]
That's risky indeed but I also think it is necessary.

**Comment by cioby23** [comment]
Hi @grossmj I have tested now with the latest version 2.1.10dev2 and it starts fine. I can load a start a topology with success but there is an issue when trying to access the console of any device which uses telnet for console connection. Below is the trace from the gns3server log file

2018-08-25 11:50:25 INFO helpers.py:441 192.168.1.3 - - [25/Aug/2018:08:50:25 +0000] "GET /v2/computes HTTP/1.1" 200 1038 "-" "GNS3 QT Client v2.1.10dev2"
2018-08-25 11:50:28 ERROR base_events.py:1591 Task exception was never retrieved
future: <Task finished coro=<AsyncioTelnetServer.run() done, defined at /usr/lib/python3.7/site-packages/gns3server/utils/asyncio/telnet_server.py:190> exception=TypeError("cannot 'yield from' a coroutine object in a non-coroutine generator")>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/telnet_server.py", line 199, in run
    yield from self._process(network_reader, network_writer, connection)
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/telnet_server.py", line 272, in _process
    data = yield from self._IAC_parser(data, network_reader, network_writer, connection)
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/telnet_server.py", line 417, in _IAC_parser
    yield from network_writer.drain()
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
2018-08-25 11:53:00 INFO helpers.py:441 192.168.1.3 - - [25/Aug/2018:08:53:00 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 540961 "-" "GNS3 QT Client v2.1.10dev2"

**Comment by grossmj** [comment]
@cioby23 thanks so much for testing. I fixed that issue now, please test again and let me know if you find other issues.

**Comment by cioby23** [comment]
@grossmj I just tested again now with the latest fixes and it works fine. Thanks for fixing this so quick.

**Comment by asazimov** [comment]
hi, i had the same errors, installed 2.1.10dev2 version still get errors. Besides I installed, reinstalled different versions of dependencies, to fix the issue, probably messed it badly. Requirements.txt is satisfied. The errors:
```
gns3server
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server===2.1.10dev2-f89d645b', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/web/web_server.py", line 26, in <module>
    import aiohttp
  File "/usr/lib/python3.7/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 13, in <module>
    from . import hdrs, helpers
  File "/usr/lib/python3.7/site-packages/aiohttp/helpers.py", line 30
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
 
```
Probably it's not because of the bug, as you have already fixed it. But i can't find the solution anywhere else. Could you help, please?

**Comment by cioby23** [comment]
I had this error too but I manually changed the line 30 from /usr/lib/python3.7/site-packages/aiohttp/helpers.py to
**ensure_future = asyncio.ensure_future**
and the the GUI started fine.

**Comment by grossmj** [comment]
This is strange because aiohttp should have handled this. What do you have if you type `pip3 freeze | grep aiohttp`?

```
pip3 freeze | grep aiohttp
aiohttp==2.3.10
aiohttp-cors==0.5.3
```

The aiohttp helpers.py file should contain something like this:

```
try:
    from asyncio import ensure_future
except ImportError:
    ensure_future = getattr(asyncio, 'async')
```

**Comment by asazimov** [comment]
Changing the line helped, 
```
pip3 freeze | grep aiohttp
aiohttp==2.2.5
aiohttp-cors==0.5.3

```
Now i can add IOSes, but they don't work i get `Error: Sorry, no idle-pc value was suitable`
  ```
Using iomem percentage: 5
                                                 \

                                                  ROM: reload requested...

!!! WARNING - VM is not running, will be unresponsive (status=1) !!!


```
```
ROMMON emulation microcode.

                           Launching IOS image at 0x80008000...
```

**Comment by grossmj** [comment]
Instead of changing the line, the solution is to use aiohttp 2.3.10.

You can install it by typing `pip3 install aiohttp==2.3.10`

@asazimov for your other problem with the IOS image, please open a new issue and provide the IOS image filename you used.

Thanks!

**Comment by grossmj** [comment]
Fixed by requiring at least aiohttp version 2.3.3 to be installed.

**Comment by asazimov** [comment]
Installed `aiohttp 2.3.10` worked fine, today i ran GNS3, first got `ModuleNotFoundError: No module named 'jsonschema'`  then i got  `ModuleNotFoundError: No module named  'wcwidth'`. now i get;  
```
gns3server 
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server===2.1.10dev2-f89d645b', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/web/route.py", line 34, in <module>
    from .response import Response
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f89d645b-py3.7.egg/gns3server/web/response.py", line 25, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```


These are my pip3 list:
```
aiohttp            2.3.10             
aiohttp-cors       0.5.3              
appdirs            1.4.3              
async-timeout      2.0.1              
attrs              18.1.0             
btrfsutil          1.0.0              
CacheControl       0.12.5             
chardet            3.0.4                        
colorama           0.3.9              
configobj          5.0.6              
distlib            0.2.7              
distro             1.3.0              
gns3-gui           2.1.10dev2-a5f4ec01
gns3-server        2.1.10dev2-f89d645b
html5lib           1.0.1              
idna               2.7                
idna-ssl           1.1.0              
isc                2.0                
Jinja2             2.10               
jsonschema         2.6.0              
lockfile           0.12.2             
MarkupSafe         1.0                
msgpack            0.5.6              
multidict          4.3.1              
packaging          17.1               
pip                18.0               
progress           1.4                
prompt-toolkit     1.0.15             
psutil             5.4.7              
pygobject          3.28.3             
pyparsing          2.2.0              
PyQt5-sip          4.19.12                     
pytoml             0.1.16             
raven              6.9.0              
requests           2.19.1             
retrying           1.3.3              
setuptools         40.2.0             
sip                4.19.12            
six                1.11.0             
team               1.0                
typing             3.6.4              
urllib3            1.23               
wcwidth            0.1.7              
webencodings       0.5.1              
yarl               1.2.6              
zipstream          1.1.4           

```

**Comment by grossmj** [comment]
Have you installed the server and gui using `python3.7 setup.py install`?

**Comment by asazimov** [comment]
i used `python3 setup.py install`

**Comment by asazimov** [comment]
Uninstalled and reinstalled 
  ```
542  git checkout 2.1
  543  sudo pip3 install -r requirements.txt
  544  sudo python3.7 setup.py install
  545  cd ../gns3-gui/
  546  git checkout 2.1
  547  sudo pip3 install -r requirements.txt
  548  sudo python3.7 setup.py install
```

i got this when i ran `install -r requirements` when i installing gns3-server
```
sudo pip3 install -r requirements.txt
Requirement already satisfied: jsonschema>=2.4.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: aiohttp<2.4.0,>=2.3.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.3.10)
Requirement already satisfied: aiohttp-cors<0.6.0,>=0.5.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: yarl>=0.11 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.2.6)
Requirement already satisfied: Jinja2>=2.7.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.10)
Requirement already satisfied: raven>=5.23.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (6.9.0)
Requirement already satisfied: psutil>=3.0.0 in /usr/lib/python3.7/site-packages/psutil-5.4.7-py3.7-linux-x86_64.egg (from -r requirements.txt (line 7)) (5.4.7)
Requirement already satisfied: zipstream>=1.1.4 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.1.4)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python3.7/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/usr/lib/python3.7/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'


```

**Comment by grossmj** [comment]
Maybe try to update pip `python3.7 -m pip install -U pip`

**Comment by asazimov** [comment]
`Requirement already up-to-date: pip in /usr/lib/python3.7/site-packages (18.0)`

**Comment by grossmj** [comment]
Very strange, try to remove `typing>=3.5.3.0 # Otherwise yarl fails with python 3.4` from the requirements.txt file and run the installation again.

Thanks! :)

**Comment by asazimov** [comment]
Removing the line and reinstalling didn't help. 
```
sudo pip3 install -r requirements.txt
Requirement already satisfied: jsonschema>=2.4.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: aiohttp<2.4.0,>=2.3.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.3.10)
Requirement already satisfied: aiohttp-cors<0.6.0,>=0.5.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: yarl>=0.11 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (1.2.6)
Requirement already satisfied: Jinja2>=2.7.3 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.10)
Requirement already satisfied: raven>=5.23.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (6.9.0)
Requirement already satisfied: psutil>=3.0.0 in /usr/lib/python3.7/site-packages/psutil-5.4.7-py3.7-linux-x86_64.egg (from -r requirements.txt (line 7)) (5.4.7)
Requirement already satisfied: zipstream>=1.1.4 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (1.1.4)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python3.7/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/usr/lib/python3.7/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
```

```
gns3server 
Traceback (most recent call last):
  File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server===2.1.10dev2-f8ecd61a', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/route.py", line 34, in <module>
    from .response import Response
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/response.py", line 25, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by asazimov** [comment]
I had previous version folders were in `/usr/lib/python3.7/site-packages `i deleted them manually reinstalled, now i get   
```
File "/usr/bin/gns3server", line 11, in <module>
    load_entry_point('gns3-server===2.1.10dev2-f8ecd61a', 'console_scripts', 'gns3server')()
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/main.py", line 82, in main
    from gns3server.run import run
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/run.py", line 32, in <module>
    from gns3server.web.web_server import WebServer
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/web_server.py", line 32, in <module>
    from .route import Route
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/route.py", line 34, in <module>
    from .response import Response
  File "/usr/lib/python3.7/site-packages/gns3_server-2.1.10dev2_f8ecd61a-py3.7.egg/gns3server/web/response.py", line 25, in <module>
    import jinja2
  File "/usr/lib/python3.7/site-packages/Jinja2-2.10-py3.7.egg/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3.7/site-packages/Jinja2-2.10-py3.7.egg/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3.7/site-packages/Jinja2-2.10-py3.7.egg/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3.7/site-packages/Jinja2-2.10-py3.7.egg/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
ModuleNotFoundError: No module named 'markupsafe'
```
