### ISSUE TITLE
None is not of type 'integer'

### ISSUE THREAD

**Issue by chopnico** [GNS3/gns3-gui#2610]
I was trying to open an existing project and I got this:

Bad request http://127.0.0.1:3080/v2/compute/projects/e4fe112e-c9b5-47ed-b720-5a7c501c4c42/qemu/nodes {
    "message": "None is not of type 'integer'\n\nFailed validating 'type' in schema['properties']['console']:\n    {'description': 'Console TCP port',\n     'maximum': 65535,\n     'minimum': 1,\n     'type': 'integer'}\n\nOn instance['console']:\n    None",
    "method": "POST",
    "path": "/v2/compute/projects/{project_id}/qemu/nodes",
    "request": {
        "acpi_shutdown": false,
        "adapter_type": "e1000",
        "adapters": 15,
        "bios_image": "",
        "boot_priority": "c",
        "cdrom_image": "",
        "cpu_throttling": 0,
        "cpus": 1,
        "hda_disk_image": "vEOS-4.20.9M-lab-combined.vmdk",
        "hda_disk_image_md5sum": "ca44503e9c3f0b9465c0f278e219faa9",
        "hda_disk_interface": "ide",
        "hdb_disk_image": "",
        "hdb_disk_interface": "ide",
        "hdc_disk_image": "",
        "hdc_disk_interface": "ide",
        "hdd_disk_image": "",
        "hdd_disk_interface": "ide",
        "initrd": "",
        "kernel_command_line": "",
        "kernel_image": "",
        "legacy_networking": false,
        "linked_clone": true,
        "mac_address": "0c:4c:42:66:fe:00",
        "options": "-enable-kvm -nographic",
        "process_priority": "normal",
        "ram": 2048,
        "usage": ""
    },
    "status": 400
}
I tried deleting a few nodes from the project file, but it didn't seem to fix it.

**Comment by chopnico** [comment]
I'm I sending this to the right place?

**Comment by grossmj** [comment]
What version of GNS3 have you used?

**Comment by chopnico** [comment]
Thanks! I wasn't sure if I should have posted this on the GNS3 support forum or this. 

Anyway, I'm currently running 2.1.11 for both server and client.

Thanks!

Wes

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/df3baffd9b69cc794df8e26a1e0ad1acf8ab4d1f

This should work in v2.1.12. In the meantime, you can edit the .gns3 in your project directory and find ```"console": null,``` entries and replace ```null``` by a value like 5000 for instance.

**Comment by chopnico** [comment]
This didn't fix the issue. The node that it's barking about already has a console port configured. But, just to cover the bases, I replaced all the nulls for each "console" with a number.

**Comment by chopnico** [comment]
Sorry, one last thing. The only way that I could get it to work again was to run gns3restore from the server. After doing so, I was able to load the project file with no problems.
