### ISSUE TITLE
symlink not being created in duplicated IOU devices or IOU projects in 2.1.12

### ISSUE THREAD

**Issue by highslater** [GNS3/gns3-gui#2699]
LINUX

The feature "Automatically create a symbolic link to the IOU image in the IOU working directory." is possibly causing problems.

This worked in 2.1.11, but not in 2.1.12 LINUX

1.) open a new project "TEST"
2.) insert an IOU router  >>> START.
3.) STOP router and save project as "TEST_COPY"
4.) START >>> ERRNO 17 "cannot create symlink, FILE EXISTS.

This happens with anything involving duplication of devices or projects.
-when a router is first created and started the symlink is properly created in the devices iou folder.
-when the project is copied or the device is duplicated the devices iou file has what it thinks is a bin file.
-if this pseudo bin file is deleted and the the duplicated device restarted the device works. Not a great
workaround for projects with 30 devices.

This sounds like the common symlink creation problem that is usually handled with 
ln -sfn /new/target /path/to/symlink
But I am guessing.

**Comment by grossmj** [comment]
Indeed symlinks were not copied when duplicating a node. This is fixed now, thanks for reporting it.

**Comment by highslater** [comment]
Ok. 
1.) I pasted this code into 2.1.12 and you can indeed duplicate a router within a project.
however this still happens when ...

2.) A project (test) is "saved as" (test_copy) using FILE > Save project as ...
[ you would do this when making a back-up copy or as a simple version control ]

3.) A project (test) is "duplicated" (test_copy) using FILE > New blank project > Projects library (select "test" > Duplicate).

2 and 3 might be the same bug.

**Comment by grossmj** [comment]
This commit should cover these cases: https://github.com/GNS3/gns3-server/commit/ae3515434c4ae10d8b64b91d3e1ab3335cd76f84

Please let me know if there is still a problem.

Thanks again!

**Comment by highslater** [comment]
The Above worked Flawlessly when using a local server.
When using a client to access an esxi gns3_vm however, it does not.
It might be the way I edited the files, however.
I am going to make a fresh VM and test that.

thanks

**Comment by odie213** [comment]
I can verify this doesn't work with gns3_vm.  I can save project A as another project B.  Shut GNS3 off, turn it all back on and only project A will start up.  Project B opens but if I try to start it, I get "could not create symbolic link" errors.  I am using 2.1.14

**Comment by grossmj** [comment]
Fixed in https://github.com/GNS3/gns3-server/commit/e291ec1eb902d0ae42e48d375e166efe8af6daf2

**Comment by odie213** [comment]
That worked!  Thanks!
