### ISSUE TITLE
[2.2.0b2] Qemu link state shows UP when no link is connected

### ISSUE THREAD

**Issue by sairuscz** [GNS3/gns3-gui#2821]
I noticed that when a QEMU VM starts in GNS3, all its links appear UP inside the VM even though no GNS3 links are connected to it. It would be great to enhance this great new feature to reflect real-world behavior. 

My test results:
-Start QEMU VM without connected link = Link status remains Up (Should be down when no link is attached)
-Shutdown directly connected device = Link status remains Up (Should be down when directly connected device is down)
-Suspend a GNS3 link = Link goes down (OK)
-Delete existing link = Link goes down (OK)

**GNS3 version and operating system :**
 - Client OS: Windows 10
 - GNS3 VM  2.2.0b2
- Tested with QEMU Fortigate VM

1)Start QEMU VM with multiple virtual interfaces
2)Check link status of all interfaces and you will see that unplugged links will report us up

Workaround:
Connect a link and then delete it. It will then appear as down in the QEMU VM.

**Comment by grossmj** [comment]
Damn, I thought we fixed this in https://github.com/GNS3/gns3-server/issues/1582

**Comment by sairuscz** [comment]
I've just tested on 2.2.0b3 and the above behavior is still the same.

**Comment by grossmj** [comment]
Ok, I will have to investigate why.

**Comment by grossmj** [comment]
@sairuscz do you use the GNS3 VM or do you run Qemu VMs directly on your host?

**Comment by sairuscz** [comment]
@grossmj : I am using the GNS3 VM for VmWare Workstation.

![image](https://user-images.githubusercontent.com/24818591/60175254-458a4180-9813-11e9-95eb-9b6275ac8a3b.png)

**Comment by sairuscz** [comment]
@grossmj you can test with FortiOS 6.2 VM Trial:
https://drive.google.com/file/d/1gqyLVf6BOcns_BUVTNPEgKFH7_HmjWCn/view?usp=sharing

Command to see Link Status in FortiOS:
diagnose hardware deviceinfo nic port1
diagnose hardware deviceinfo nic port2
...

**Comment by grossmj** [comment]
Thanks for sharing. I quickly tested and indeed there is something wrong with the Qemu link states. I will investigate more later.

**Comment by b-ehlers** [comment]
The following is tested with v2.1, applying my patch from <https://github.com/GNS3/gns3-server/issues/1582>. As it's a different environment, my findings may not apply to v2.2.

I've got the same issue, a FortiGate VM without any connection sees all it's interfaces as UP:
```
FortiGate-VM64-KVM # diagnose hardware deviceinfo nic port1 | grep ^[SL][ti]
State:		 up
Link:		 up
```

 I then connected manually to the QEMU monitor and set the link state of port1 (gns3-0 in QEMU) to off:
`(qemu) set_link gns3-0 off`
But that didn't change the interface state in the FortiGate VM.

Then I changed the link state to on, then off:
`(qemu) set_link gns3-0 on`
`(qemu) set_link gns3-0 off`

This time it has the expected result, the qemu commands are working fine:
```
FortiGate-VM64-KVM # diagnose hardware deviceinfo nic port1 | grep ^[SL][ti]
State:		 up
Link:		 down
```

So my current theory is, that GNS3 correctly tells QEMU to set the interface status to down, otherwise the first `set_link gns3-0 off` would have some effect. But the FortiGate VM seems to ignore the link state at boot, so all interfaces are shown as UP.

Then I changed the network type of the FortiGate VM from "Paravirtualized Network I/O (virtio-net-pci)" to "Intel Gigabit Ethernet (e1000)". Now the FortiGate VM behaves as expected, all unconnected ports are DOWN.

Now I tested with the Micro Core Linux VM, changing the network type to "Paravirtualized Network I/O (virtio-net-pci)" and the number of interfaces to 10. This time the interface status is shown correctly, all unconnected interfaces are down after boot:
```
gns3@box:~$ ip link | grep eth[0-9]
5: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
6: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
7: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
8: eth3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
9: eth4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
10: eth5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
11: eth6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
12: eth7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
13: eth8: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
14: eth9: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
```

So the "Paravirtualized Network I/O (virtio-net-pci)" network type is working fine in this VM.

My result: Some VMs (with some network types) don't get the link state at boot and I'm pessimistic that this can be fixed easily.

**Comment by grossmj** [comment]
@b-ehlers thanks so much for these findings! 

The only easy thing we can do for now is to change the default NIC to e1000 for the FortiGate VM appliance.

**Comment by grossmj** [comment]
@sairuscz I have seen that all other Fortinet appliances use virtio-net-pci, have you had a chance to try any of them?

**Comment by sairuscz** [comment]
@grossmj 
Based on the official documentation all Fortinet VMs should use "virtio" adapter on KVM:

```
https://docs.fortinet.com/vm/kvm/fortigate/6.2/kvm-cookbook/6.2.0/659352/deploying-the-fortigate-vm
https://docs.fortinet.com/vm/kvm/fortianalyzer/6.2/fortianalyzer-vm-on-kvm/6.2.0/553674/configuring-hardware-settings
https://docs.fortinet.com/vm/kvm/fortiweb/6.1/fortiweb-vm-on-kvm/6.1.1/56544/import-the-fortiweb-vm-virtual-machine
```

However,  virtio does not seem to be supported by QEMU (3.1.0) as I get the bellow error messages:
```
Execution log:
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: -device virtio,mac=0c:86:f7:8b:a1:00,netdev=gns3-0: 'virtio' is not a valid device model name
```


I'v tested the the  link status behavior of bellow appliances with no links connected in GNS3:

```
Fortigate VM 6.2.0 (10x virtio-net-pci) - all ports UP (PROBLEM)
Fortigate VM 6.2.0 (4x virtio-net-pci) - all ports UP (PROBLEM)
FortiAuthenticator VM 6.0.2 (4x virtio-net-pci) - port1-3 DOWN, last interface UP (PROBLEM)
FortiADC VM 5.2.2 (4x virtio-net-pci) - all ports DOWN (OK)

Fortigate VM 6.2.0 (10x e1000) - all ports DOWN (OK)
Fortigate VM 6.2.0 (4x e1000) - all ports DOWN (OK)
FortiAuthenticator VM 6.0.2 (4x e1000) - all ports DOWN (OK)
FortiADC VM 5.2.2 (4x e1000) - all ports DOWN (OK)
```

Based on the test I think it is safe to set all Fortinet VMs to use e1000 adapter as default. 

Using e1000 could potentially cause that only one CPU core will be used while processing high amount traffic, however I think that is hardly a concern in GNS3 environment with nested virtualization.

**Comment by DragonWin** [comment]
Hi, Just my 2 cent.

Testing with 2.2 B4 with other Fortinet devices, I each one needs to be tested for which works, as e.g. FortiMail does not work with e1000 but works fine with virtio_net-pci.

Here are my results.
FortiMail 6.0.3
virtio_net-pci = link state working  (OK)
e1000 = No packets reaches the appliance  (PROBLEM)

FortiCache 4.2.7
virtio_net-pci = Link in port1 also gives link on port3 (PROBLEM)
e1000 = link state working (OK)

FortiWeb 6.0.0
virtio_net-pci = link state working (OK)
e1000 = Always link on port4 (PROBLEM)

FortiProxy 1.0.2
virtio_net-pci = Link state working (OK)
e1000 = Always link on port10 (PROBLEM)

FortiHypervisor 1.1.0
virtio_net-pci = Link state working (OK)
e1000 = Link state working (OK)

**Comment by grossmj** [comment]
> However, virtio does not seem to be supported by QEMU (3.1.0) as I get the bellow error messages

virtio is legacy I believe. We should use virtio_net-pci will all the recent Qemu versions.

I have created a PR (https://github.com/GNS3/gns3-registry/pull/451/files) to have Fortigate VM, FortiCache, Fortiauthenticator and Fortianalyzer use e1000.

**Comment by grossmj** [comment]
I think we are good with this now.
