### ISSUE TITLE
Double error messages with remote GNS3VM

### ISSUE THREAD

**Issue by b-ehlers** [GNS3/gns3-gui#3011]
**Describe the bug**
When I configure a remote server and use that as a GNS3VM each error is shown twice.

This does not happen with devices in the local server and in normal GNS3VMs.

**GNS3 version and operating system (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - GNS3 version 2.2.10
 - GNS3VM configured as a remote server

Normal local main server:
![local_main_server](https://user-images.githubusercontent.com/49040325/85927091-2568e480-b8a4-11ea-9c81-1a7da38ed487.png)

Remote server, for demonstration I'm using a standard GNS3VM in VMware fusion as the remote server:
![remote_server](https://user-images.githubusercontent.com/49040325/85927095-2dc11f80-b8a4-11ea-9baa-ee2770b011a4.png)

Remote VM as a GNS3VM:
![remote_gns3vm](https://user-images.githubusercontent.com/49040325/85927098-31ed3d00-b8a4-11ea-8709-ebe83ff58d07.png)

**To Reproduce**
1. Configure remote server and remote GNS3VM as shown above
2. Stop GNS3 and start again to have a stable environment
3. Add a dynamips template in the GNS3VM
4. Create a project and add the dynamips node running in the GNS3VM
5. Start it
6. Create an error, for example `pkill dynamips` in the GNS3VM
7. The error message is shown twice

**Screenshots or videos**
![gui_screenshot](https://user-images.githubusercontent.com/49040325/85927247-1fbfce80-b8a5-11ea-805e-ffa0fe906e16.png)

**Additional context**

I assume that happens, because for remote GNS3VMs two notification streams are created, one for the remote server and one for the GNS3VM.

```
/Users/behlers# grep notifications ~/.config/GNS3/2.2/gns3_server.log
2020-06-27 18:15:56 INFO compute.py:430 Connected to compute WebSocket 'http://172.20.1.1:3080/v2/compute/notifications/ws'
2020-06-27 18:15:56 INFO compute.py:430 Connected to compute WebSocket 'http://172.20.1.131:80/v2/compute/notifications/ws'
2020-06-27 18:16:06 INFO compute.py:430 Connected to compute WebSocket 'http://172.20.1.131:80/v2/compute/notifications/ws'
```

**Comment by grossmj** [comment]
Should be fixed now.

**Comment by b-ehlers** [comment]
> Should be fixed now.

Sad enough, it's not fixed.

I just downloaded the nighly build 2020-070-08 of v2.2 from SourceForge and re-tested. While #3010 is fixed (thanks for that), this issue is still present.

For me that's not surprising as this issue has nothing to do with the debug function, I haven't activated debuggung during this issue.

> This does not happen with devices in the local server and in normal GNS3VMs.

This issue doesn't happen always, I noticed it only when I'm using a remote GNS3 VM.

**Comment by grossmj** [comment]
> Sad enough, it's not fixed.

Must be because I haven't properly tested using a GNS3 VM. I will have a closer look then.

**Comment by b-ehlers** [comment]
Please note, that normal GNS3 VMs (using a virtualization engine) don't have this issue. Only GNS3 VMs using a remote VM are affected.

**Comment by grossmj** [comment]
I know we have had a issue with building our macOS version yesterday. Can you confirm this problem is still there in https://sourceforge.net/projects/gns-3/files/Nightly%20Builds/2020-07-08/2.2/GNS3-2.2.11dev1.dmg/download ?

Thanks.

**Comment by grossmj** [comment]
> I assume that happens, because for remote GNS3VMs two notification streams are created, one for the remote server and one for the GNS3VM.

Correct, I could reproduce the problem. This will need some careful refactoring since we could easily break something here.

```
2020-07-09 20:13:38 INFO compute.py:430 Connected to compute 'ff035757-1d5b-4451-a01d-c29c11701068' WebSocket 'http://172.16.9.128:80/v2/compute/notifications/ws'
2020-07-09 20:13:38 INFO compute.py:430 Connected to compute 'vm' WebSocket 'http://172.16.9.128:80/v2/compute/notifications/ws'
```

**Comment by b-ehlers** [comment]
> This will need some careful refactoring since we could easily break something here.

Perhaps the milestone could be shifted to 2.3 or even later. For me this is more of a nuisance than a serious problem

**Comment by grossmj** [comment]
> Perhaps the milestone could be shifted to 2.3 or even later. For me this is more of a nuisance than a serious problem

Agreed, we are in the process to work on a new back-end and this could be solved at that time.
