### ISSUE TITLE
Bug in windows versions of GNS3 3.0 a1

### ISSUE THREAD

**Issue by aksplease** [GNS3/gns3-gui#3373]
### Discussed in https://github.com/GNS3/gns3-gui/discussions/3370

<div type='discussions-op-text'>

<sup>Originally posted by **aksplease** August  9, 2022</sup>
hi Develop team ,

please address the issues faced in new gns3 3.0 alpha release 

not able to add a VMware instance ,might be this happening as the gns3 app not able to detect VMware location automatically. as during starting the app it was not automatically starting the VMware.

when gns3 app is started it not firing the gns3 VMware and gns3vm to start as its doing in  earlier version(might be location mapping issue )

readding the IOS for 7200 router did not gave a error but create error for 3745 series 

after uploading IOS it not sensing IOS presence one closing and staring again the uploading page sensing the IOS 

router is not being active on start ..

please go through the the error snapshots and find out errors with care 

it will be nice to make a small operational manual  about  the new features 
and how to work with new version .as there are many changes in new version … 

![IOS running issue](https://user-images.githubusercontent.com/11521667/183597345-5bc19db0-9f15-4be1-9697-1ede146f2a96.jpg)
![IOS UPLOAD ERROR](https://user-images.githubusercontent.com/11521667/183597358-55f791e3-2f58-442b-8c5d-9134828fb36f.jpg)
![IOS UPLOAD ERROR2](https://user-images.githubusercontent.com/11521667/183597363-720f3f26-cdd5-48a4-8aa8-ea674992fd17.jpg)
![IOS UPLOAD ERROR3](https://user-images.githubusercontent.com/11521667/183597366-21502e48-7119-4c32-b77d-54a049f220fa.jpg)
![VM instance error1](https://user-images.githubusercontent.com/11521667/183597372-929e9e9b-b407-461f-b08f-550d3a6b86fd.jpg)
</div>

**Comment by grossmj** [comment]
> not able to add a VMware instance ,might be this happening as the gns3 app not able to detect VMware location automatically. as during starting the app it was not automatically starting the VMware.

We do not start VMs automatically anymore. Please manually start the VM first before GNS3.

I have fixed the others issues you reported. Let us know if you find more bugs in v3.0 alpha 2

**Comment by aksplease** [comment]
sorry Jeremy 
issue still persists

![image](https://user-images.githubusercontent.com/11521667/189109943-358bb38e-b10e-4d4b-b385-d22415ef61dd.png)
![GNS#3 ALPHA-2 ERROR](https://user-images.githubusercontent.com/11521667/189110190-578a9d8d-e846-4882-bc93-2eb37cffea3f.jpg)

same behavior of gns3 VM as it was earlier and same are the issue

**Comment by aksplease** [comment]
Hi Jeremy,

Can this Dynamips Cisco IOS Checksum check be bypassed in 2.2.34 serios of gns3 as its not let the IOS to be installed the Routers.pls go through the images 



![Gns3 Error CheksumErr](https://user-images.githubusercontent.com/11521667/189351136-ca437de0-3170-436d-99f8-1390b1359159.jpg)

**Comment by cristian-ciobanu** [comment]
Indeed there is a bug in GNS3 3.0.0 alpha2 when trying to add an IOS image using the wizard

![image](https://user-images.githubusercontent.com/7124193/189379640-50883bc3-7486-4a51-b978-0687530ca5ae.png)

After it find the image and I click Install on the next page when I click on the Next button it asks me for confirmation I select Yes and a crash report is generated

=== GNS3 3.0.0a2 traceback on 09 sep 2022 17:56:38 ===
TypeError: invalid result from ApplianceWizard.validateCurrentPage(), a 'bool' is expected not 'NoneType'

**Comment by jonimaka** [comment]
I'm having the similar problems. I'm running gns3 in ubuntu in vmware workstation 15 player. My gns3server disappearred. I used the https://docs.gns3.com/docs/using-gns3/administration/running-gns3-server-as-daemon to try and restore a gns3server. When i open a network project and try and start the routers with the green triangle I get the message: ghost-c3745-advipservicesk9-mz.124-25d.image-256.ghost is an invalid name to create a Dynamips node, and nothing starts. When I press the 'reload all nodes' in the top ribbon I get the ghost-c3745-advipservicesk9-mz.124-25d.image-256.ghost is an invalid name to create a Dynamips node  This has only happened over this week. May the answer is to start again?? Is there a way of uninstalling everything that belongs to GNS3 from Ubuntu (apart from my projects and router,firewall and other device images I have)?

**Comment by jonimaka** [comment]
Forgot to say, when i right click an individual router and press the reload, the individual router starts fine and i can console into it.

**Comment by josephmhiggins** [comment]
@jonimaka,
I am engaged.
I think I know the solution for **your** problem.
Your problem appears to be different than the OP, @aksplease , problem.
It appears that you want to "rollback" you upgrade to a different version of GNS3..
I rate your problem as of extremely high importance and I **think** my solution will work.
I am not saying my idea will work, but my confidence level is extremely high that it will work.
Your problem is not a gns3 developer problem, but it should be relegated to the GNS3 community forum.
I will handle it there. I hope my idea works because it is a game-changer.

**Comment by aksplease** [comment]
hi josephmhiggins,

i think i have raised two issues in a single case .that's why u are confused.

1.  1st is with version 3.0 where IOS are are not properly sensed and not running well (Here i completely uninstalled stable version of gns3 in my windows machine and installed the 3.0 alpha version and share you the snapshot of problems i faced .

2.  2nd case is the IOS case sensitivity which is existing  in every version of gns3 released (where the project don't load for a missing Specific  IOS,i think this should be come as  warning with option whether user want to load project instead of the IOS being missed which he can later load the IOS in Gns3 VM manually or replaced with the available image series with user.)it will help user not to specifically bound to particular exact series of image ...

Regards

**Comment by josephmhiggins** [comment]
aks,
re: item 2
I did this is the ensuing post on the GNS3 community forum. I do not have the time right now to fix this up. It will take at least 40 hours for me to fix it and for it to be presentable. But the idea works. The code will should be folded into an API instance. 
https://gns3.com/community/featured/quick-powershell-to-investigate-import-projects-from-gns3-marketplace

As far as giving users the ability to select a replacement image for a missing image - that is not something I will even attempt  within the next 9months. I believe another poster wanted a User Input box to replace dynamips images and he posted it here somewhere on github.

That was a complete non-starter for me because I know that it would be at least 160hours to go through dynamips images - and I do not support dynamips images anyways.

You are making the mistake that "marketplace labs are for other gns3 users" when, in fact, marketplace labs are for the gns3 users posting the labs because they are learning also. One of the best ways to learn is to teach....So...as long as someone gives constructive criticism about a lab - it's a win-win. But if you do not get a lab that is "up to your specifications", then you should tell the poster what he did wrong - so the poster can learn.

**Comment by grossmj** [comment]
Please try with 3.0 alpha 3, the issue should be gone.
