### ISSUE TITLE
Missing topology_schema.json

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#415]
Just installed GNS3 v1.4.0dev1 on Linux Debian 8, the installation went smooth:
```
sudo pyvenv --system-site-packages /opt/GNS3
sudo sh -c '. /opt/GNS3/bin/activate && python3 setup.py install'
```

When I create a new project, I get the following error:
![gns3-save-missing-topology_schema](https://cloud.githubusercontent.com/assets/896406/8083608/1f14ea42-0f86-11e5-8361-3007ced027f4.png)

When I manually create the directory /opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.4.0.dev1-py3.4.egg/resources and copy topology_schema.json into it, the error goes away.

Another problem with the topology validation, maybe it's connected:
When I create a project, put a router into it, e.g. cisco 3725 and save it, I get the following error message:
```
GNS3 management console. Running GNS3 version 1.4.0.dev1 on Linux (64-bit) with Qt 5.3.2.
Copyright (c) 2006-2015 GNS3 Technologies.

=> {'platform': 'c3725', 'iomem': 5, 'mmap': True, 'nvram': 256, 'idlemax': 500, 'sparsemem': True, 'console': 2001, 'slot0': 'GT96100-FE', 'disk0': 0, 'startup_config': 'configs/i1_startup-config.cfg', 'mac_addr': 'c201.10fa.0000', 'disk1': 0, 'idlepc': '0x602467a4', 'ram': 128, 'system_id': 'FTX0945W0MY', 'name': 'R1', 'auto_delete_disks': False, 'clock_divisor': 8, 'exec_area': 64, 'idlesleep': 30, 'image': 'c3725-adventerprisek9-mz.124-25d.image'} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['topology']['properties']['nodes']['items']['properties']['properties']:
    {'oneOf': [{'$ref': '#/definitions/properties_vpcs'},
               {'$ref': '#/definitions/properties_dynamips'},
               {'$ref': '#/definitions/properties_qemu'},
               {'$ref': '#/definitions/properties_virtualbox'},
               {'$ref': '#/definitions/properties_iou'}],
     'type': 'object'}

On instance['topology']['nodes'][0]['properties']:
    {'auto_delete_disks': False,
     'clock_divisor': 8,
     'console': 2001,
     'disk0': 0,
     'disk1': 0,
     'exec_area': 64,
     'idlemax': 500,
     'idlepc': '0x602467a4',
     'idlesleep': 30,
     'image': 'c3725-adventerprisek9-mz.124-25d.image',
     'iomem': 5,
     'mac_addr': 'c201.10fa.0000',
     'mmap': True,
     'name': 'R1',
     'nvram': 256,
     'platform': 'c3725',
     'ram': 128,
     'slot0': 'GT96100-FE',
     'sparsemem': True,
     'startup_config': 'configs/i1_startup-config.cfg',
     'system_id': 'FTX0945W0MY'}

Validation error when dumping the topology.
It's probably a false positive but please send the .gns3 to developers@gns3.net.
Thanks !
```

**Comment by ehlers** [comment]
Oh, I forget the .gns3 file:
```
{
    "auto_start": false,
    "name": "a",
    "project_id": "3ea28c95-04eb-42b5-a6c3-a320136bc22d",
    "resources_type": "local",
    "revision": 4,
    "topology": {
        "nodes": [
            {
                "description": "Router c3725",
                "dynamips_id": 1,
                "id": 1,
                "label": {
                    "color": "#ff000000",
                    "font": "TypeWriter,10,-1,5,75,0,0,0,0,0",
                    "text": "R1",
                    "x": 19.5,
                    "y": -25.0
                },
                "ports": [
                    {
                        "adapter_number": 0,
                        "id": 1,
                        "name": "FastEthernet0/0",
                        "port_number": 0
                    },
                    {
                        "adapter_number": 0,
                        "id": 2,
                        "name": "FastEthernet0/1",
                        "port_number": 1
                    }
                ],
                "properties": {
                    "auto_delete_disks": false,
                    "clock_divisor": 8,
                    "console": 2001,
                    "disk0": 0,
                    "disk1": 0,
                    "exec_area": 64,
                    "idlemax": 500,
                    "idlepc": "0x602467a4",
                    "idlesleep": 30,
                    "image": "c3725-adventerprisek9-mz.124-25d.image",
                    "iomem": 5,
                    "mac_addr": "c201.10fa.0000",
                    "mmap": true,
                    "name": "R1",
                    "nvram": 256,
                    "platform": "c3725",
                    "ram": 128,
                    "slot0": "GT96100-FE",
                    "sparsemem": true,
                    "startup_config": "configs/i1_startup-config.cfg",
                    "system_id": "FTX0945W0MY"
                },
                "server_id": 1,
                "type": "C3725",
                "vm_id": "46976a00-547a-4aa6-a4b6-8c3a13b1e9d4",
                "x": -111.0,
                "y": -23.0
            }
        ],
        "servers": [
            {
                "cloud": false,
                "host": "192.168.1.11",
                "id": 1,
                "local": true,
                "port": 8000,
                "protocol": "http"
            }
        ]
    },
    "type": "topology",
    "version": "1.4.0.dev1"
}
```

**Comment by noplay** [comment]
I'm on it!

**Comment by noplay** [comment]
It should be fixed for the console error. And I hope install work fine now I have force the file to be include during the installation

**Comment by ehlers** [comment]
I re-installed, but topology_schema.json is still not copied. Maybe because the resources folder is not in the gns3 subdirectory but in the base directory.

**Comment by noplay** [comment]
Ok I moved it as a subfolder of gns3 directory

**Comment by ehlers** [comment]
Now I have the file twice (better as nothing :-), I really removed the /opt/GNS3 directory and made a clean install:
```
behlers@dell:~/GNS3/GNS3/gns3-gui$ find /opt/GNS3 -name "topo*json" | xargs ls -l
-rw-r--r-- 1 root root 19393 Jun 10 17:24 /opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.4.0.dev1-py3.4.egg/gns3/resources/topology_schema.json
-rw-r--r-- 1 root root 19393 Jun 10 17:24 /opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.4.0.dev1-py3.4.egg/gns3/schemas/topology.json
```

Furthermore I get an error on starting GNS3:
```
Traceback (most recent call last):
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.4.0.dev1-py3.4.egg/gns3/main_window.py", line 1144, in startupLoading
    if servers.initLocalServer() and servers.startLocalServer():
  File "/opt/GNS3/lib/python3.4/site-packages/gns3_gui-1.4.0.dev1-py3.4.egg/gns3/servers.py", line 252, in initLocalServer
    sock.bind((server.host, 0))
TypeError: Can't convert 'method' object to str implicitly
```

**Comment by ehlers** [comment]
Sorry, the double installation of topo*json was my fault, I did'nt clear the build directory.

**Comment by noplay** [comment]
It should be ok for the traceback.

**Comment by ehlers** [comment]
Whow, that did it.

Just a question about the topology validation:
The cisco 3275 is OK now, but there are a lot of other devices with validation errors: Cisco 7200, IOU, QEMU. How should I report this ?

**Comment by noplay** [comment]
Make a zip with your .gns3 and send it to julien@gns3.net. I will test them and extract the error. 

We know this will arrive, the time for us to collect all the possibility of the .gns3 file :) Next step one day it's to document his content.

You can drop me all the .gns3 I will filter what is working and what is not working.
