### ISSUE TITLE
Can't load another project after connection error to remote server

### ISSUE THREAD

**Issue by ehlers** [GNS3/gns3-gui#851]
GNS3 version 1.4.0rc1 (latest unstable commit) on Linux (64-bit) with Python 3.4.2 Qt 5.3.2 and
GNS3 version 1.4.0rc1 (lastest unstable commit) on Darwin (64-bit) with Python 3.5.0 Qt 5.5.1.

Continuation of issue https://github.com/GNS3/gns3-gui/issues/833 .

Same situation as in issue https://github.com/GNS3/gns3-gui/issues/833, I get an connection error to a remote server (e.g. because it's down). But now I try to load another project, which doesn't work. The request is simply ignored without any error message.

It looks like the erroneous project can't be closed and therefore the new one isn't opened.

Furthermore the fix for issue https://github.com/GNS3/gns3-gui/issues/833 has the very bad side effect, that the local server is no longer closed on exit of the GUI.

Here a log where I just start the GUI and then stop it:
```
/Users/behlers# ps ax | grep gns
 4034 s000  S+     0:00.00 grep gns
/Users/behlers# gns3 --debug
GNS3 GUI version 1.4.0rc1
Copyright (c) 2007-2015 GNS3 Technologies Inc.
2015-12-02 13:05:03 INFO logger.py:107 Log level: DEBUG
2015-12-02 13:05:03 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2015-12-02 13:05:03 INFO servers.py:611 New remote server connection http://192.168.1.11:8000 registered
2015-12-02 13:05:03 INFO servers.py:611 New remote server connection http://192.168.1.90:8000 registered
2015-12-02 13:05:03 INFO servers.py:85 New local server connection http://192.168.1.10:8000 registered
2015-12-02 13:05:03 INFO __init__.py:177 VPCS module reset
2015-12-02 13:05:03 INFO __init__.py:320 Dynamips module reset
2015-12-02 13:05:03 INFO __init__.py:255 IOU module reset
2015-12-02 13:05:03 INFO __init__.py:249 QEMU module reset
2015-12-02 13:05:03 INFO __init__.py:283 VirtualBox module reset
2015-12-02 13:05:03 INFO __init__.py:340 VMware module reset
2015-12-02 13:05:03 INFO __init__.py:188 Docker module reset
2015-12-02 13:05:03 INFO __init__.py:70 Built-in module reset
2015-12-02 13:05:03 INFO topology.py:396 Topology reset
2015-12-02 13:05:04 DEBUG http_client.py:317 Synchronous get http://192.168.1.10:8000/v1/version with user bGLTSCln7yq0Z98DYeFzEGALFHqePZnUQVwsakCvXYDUcQj8bU53KDeXojKV7zeD
2015-12-02 13:05:04 INFO servers.py:474 Starting local server process with "/usr/local/bin/gns3server" --host=192.168.1.10 --port=8000 --local --debug --log="/Users/behlers/.config/GNS3/gns3_server.log"
2015-12-02 13:05:04 INFO servers.py:487 Local server process has started (PID=4038)
2015-12-02 13:05:04 DEBUG analytics.py:77 Stats is turn off ignore call Setup Wizard
2015-12-02 13:05:04 DEBUG analytics.py:77 Stats is turn off ignore call Main Window
2015-12-02 13:05:04 INFO __init__.py:177 VPCS module reset
2015-12-02 13:05:04 INFO __init__.py:320 Dynamips module reset
2015-12-02 13:05:04 INFO __init__.py:255 IOU module reset
2015-12-02 13:05:04 INFO __init__.py:249 QEMU module reset
2015-12-02 13:05:04 INFO __init__.py:283 VirtualBox module reset
2015-12-02 13:05:04 INFO __init__.py:340 VMware module reset
2015-12-02 13:05:04 INFO __init__.py:188 Docker module reset
2015-12-02 13:05:04 INFO __init__.py:70 Built-in module reset
2015-12-02 13:05:04 INFO topology.py:396 Topology reset
2015-12-02 13:05:28 DEBUG main_window.py:1031 Close the main Windows
2015-12-02 13:05:28 DEBUG main_window.py:1038 Project is not closed, closing the main windows
2015-12-02 13:05:28 DEBUG get_resource.py:39 Clean egg cache /var/folders/qy/g6blgc5n7y93pzg61zyt7cmr0000gn/T/tmp6tp1u6iq
/Users/behlers# ps ax | grep gns
 4038 s000  S      0:00.54 /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/Python /usr/local/bin/gns3server --host=192.168.1.10 --port=8000 --local --debug --log=/Users/behlers/.config/GNS3/gns3_server.log
 4041 s000  S+     0:00.00 grep gns
/Users/behlers#
```

**Comment by ehlers** [comment]
The gns3server keeps running only when no project is active at GUI exit. With an active project the server is shut down at exit of the GUI.

**Comment by noplay** [comment]
I think fixing the case of ghost server after a crash will fix the problem at exit. And perhaps this could reduce the number of case if the server correctly exit when the parent process die.

#838

**Comment by noplay** [comment]
Fixed thanks for the report

**Comment by ehlers** [comment]
Sorry to intervene, but issue https://github.com/GNS3/gns3-gui/issues/854 is fixed, but that was just the smaller problem for me. I normally start GNS3 to use it with some projects.

The main issue (can't load another project after connection error to remote server) is still there.

**Comment by ehlers** [comment]
Sorry, I'm totally wrong. I have missed the latest commit https://github.com/GNS3/gns3-gui/commit/112b05c3dd41ddbc0683356dec716fbba4618a3a, therefore I have still experienced that issue.

Checking with the lastest unstable commit indeed shows, that the issue is fixed. Sorry for creating confusion.
